'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class search2
    Inherits DataSet
    
    Private tableA_MUSIC_ALBUM As A_MUSIC_ALBUMDataTable
    
    Private tableA_MUSIC_STOCK As A_MUSIC_STOCKDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("A_MUSIC_ALBUM")) Is Nothing) Then
                Me.Tables.Add(New A_MUSIC_ALBUMDataTable(ds.Tables("A_MUSIC_ALBUM")))
            End If
            If (Not (ds.Tables("A_MUSIC_STOCK")) Is Nothing) Then
                Me.Tables.Add(New A_MUSIC_STOCKDataTable(ds.Tables("A_MUSIC_STOCK")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property A_MUSIC_ALBUM As A_MUSIC_ALBUMDataTable
        Get
            Return Me.tableA_MUSIC_ALBUM
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property A_MUSIC_STOCK As A_MUSIC_STOCKDataTable
        Get
            Return Me.tableA_MUSIC_STOCK
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As search2 = CType(MyBase.Clone,search2)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("A_MUSIC_ALBUM")) Is Nothing) Then
            Me.Tables.Add(New A_MUSIC_ALBUMDataTable(ds.Tables("A_MUSIC_ALBUM")))
        End If
        If (Not (ds.Tables("A_MUSIC_STOCK")) Is Nothing) Then
            Me.Tables.Add(New A_MUSIC_STOCKDataTable(ds.Tables("A_MUSIC_STOCK")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableA_MUSIC_ALBUM = CType(Me.Tables("A_MUSIC_ALBUM"),A_MUSIC_ALBUMDataTable)
        If (Not (Me.tableA_MUSIC_ALBUM) Is Nothing) Then
            Me.tableA_MUSIC_ALBUM.InitVars
        End If
        Me.tableA_MUSIC_STOCK = CType(Me.Tables("A_MUSIC_STOCK"),A_MUSIC_STOCKDataTable)
        If (Not (Me.tableA_MUSIC_STOCK) Is Nothing) Then
            Me.tableA_MUSIC_STOCK.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "search2"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/search2.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableA_MUSIC_ALBUM = New A_MUSIC_ALBUMDataTable
        Me.Tables.Add(Me.tableA_MUSIC_ALBUM)
        Me.tableA_MUSIC_STOCK = New A_MUSIC_STOCKDataTable
        Me.Tables.Add(Me.tableA_MUSIC_STOCK)
    End Sub
    
    Private Function ShouldSerializeA_MUSIC_ALBUM() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializeA_MUSIC_STOCK() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub A_MUSIC_ALBUMRowChangeEventHandler(ByVal sender As Object, ByVal e As A_MUSIC_ALBUMRowChangeEvent)
    
    Public Delegate Sub A_MUSIC_STOCKRowChangeEventHandler(ByVal sender As Object, ByVal e As A_MUSIC_STOCKRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class A_MUSIC_ALBUMDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnITEM_ID As DataColumn
        
        Private columnALBUM_NAME As DataColumn
        
        Private columnARTIST As DataColumn
        
        Private columnCATEGORY_ID As DataColumn
        
        Private columnLANGUAGE As DataColumn
        
        Friend Sub New()
            MyBase.New("A_MUSIC_ALBUM")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_IDColumn As DataColumn
            Get
                Return Me.columnITEM_ID
            End Get
        End Property
        
        Friend ReadOnly Property ALBUM_NAMEColumn As DataColumn
            Get
                Return Me.columnALBUM_NAME
            End Get
        End Property
        
        Friend ReadOnly Property ARTISTColumn As DataColumn
            Get
                Return Me.columnARTIST
            End Get
        End Property
        
        Friend ReadOnly Property CATEGORY_IDColumn As DataColumn
            Get
                Return Me.columnCATEGORY_ID
            End Get
        End Property
        
        Friend ReadOnly Property LANGUAGEColumn As DataColumn
            Get
                Return Me.columnLANGUAGE
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As A_MUSIC_ALBUMRow
            Get
                Return CType(Me.Rows(index),A_MUSIC_ALBUMRow)
            End Get
        End Property
        
        Public Event A_MUSIC_ALBUMRowChanged As A_MUSIC_ALBUMRowChangeEventHandler
        
        Public Event A_MUSIC_ALBUMRowChanging As A_MUSIC_ALBUMRowChangeEventHandler
        
        Public Event A_MUSIC_ALBUMRowDeleted As A_MUSIC_ALBUMRowChangeEventHandler
        
        Public Event A_MUSIC_ALBUMRowDeleting As A_MUSIC_ALBUMRowChangeEventHandler
        
        Public Overloads Sub AddA_MUSIC_ALBUMRow(ByVal row As A_MUSIC_ALBUMRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddA_MUSIC_ALBUMRow(ByVal ITEM_ID As String, ByVal ALBUM_NAME As String, ByVal ARTIST As String, ByVal CATEGORY_ID As String, ByVal LANGUAGE As String) As A_MUSIC_ALBUMRow
            Dim rowA_MUSIC_ALBUMRow As A_MUSIC_ALBUMRow = CType(Me.NewRow,A_MUSIC_ALBUMRow)
            rowA_MUSIC_ALBUMRow.ItemArray = New Object() {ITEM_ID, ALBUM_NAME, ARTIST, CATEGORY_ID, LANGUAGE}
            Me.Rows.Add(rowA_MUSIC_ALBUMRow)
            Return rowA_MUSIC_ALBUMRow
        End Function
        
        Public Function FindByALBUM_NAME(ByVal ALBUM_NAME As String) As A_MUSIC_ALBUMRow
            Return CType(Me.Rows.Find(New Object() {ALBUM_NAME}),A_MUSIC_ALBUMRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As A_MUSIC_ALBUMDataTable = CType(MyBase.Clone,A_MUSIC_ALBUMDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New A_MUSIC_ALBUMDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnITEM_ID = Me.Columns("ITEM_ID")
            Me.columnALBUM_NAME = Me.Columns("ALBUM_NAME")
            Me.columnARTIST = Me.Columns("ARTIST")
            Me.columnCATEGORY_ID = Me.Columns("CATEGORY_ID")
            Me.columnLANGUAGE = Me.Columns("LANGUAGE")
        End Sub
        
        Private Sub InitClass()
            Me.columnITEM_ID = New DataColumn("ITEM_ID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnITEM_ID)
            Me.columnALBUM_NAME = New DataColumn("ALBUM_NAME", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnALBUM_NAME)
            Me.columnARTIST = New DataColumn("ARTIST", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnARTIST)
            Me.columnCATEGORY_ID = New DataColumn("CATEGORY_ID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCATEGORY_ID)
            Me.columnLANGUAGE = New DataColumn("LANGUAGE", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLANGUAGE)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnALBUM_NAME}, true))
            Me.columnALBUM_NAME.AllowDBNull = false
            Me.columnALBUM_NAME.Unique = true
        End Sub
        
        Public Function NewA_MUSIC_ALBUMRow() As A_MUSIC_ALBUMRow
            Return CType(Me.NewRow,A_MUSIC_ALBUMRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New A_MUSIC_ALBUMRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(A_MUSIC_ALBUMRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.A_MUSIC_ALBUMRowChangedEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_ALBUMRowChanged(Me, New A_MUSIC_ALBUMRowChangeEvent(CType(e.Row,A_MUSIC_ALBUMRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.A_MUSIC_ALBUMRowChangingEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_ALBUMRowChanging(Me, New A_MUSIC_ALBUMRowChangeEvent(CType(e.Row,A_MUSIC_ALBUMRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.A_MUSIC_ALBUMRowDeletedEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_ALBUMRowDeleted(Me, New A_MUSIC_ALBUMRowChangeEvent(CType(e.Row,A_MUSIC_ALBUMRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.A_MUSIC_ALBUMRowDeletingEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_ALBUMRowDeleting(Me, New A_MUSIC_ALBUMRowChangeEvent(CType(e.Row,A_MUSIC_ALBUMRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveA_MUSIC_ALBUMRow(ByVal row As A_MUSIC_ALBUMRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class A_MUSIC_ALBUMRow
        Inherits DataRow
        
        Private tableA_MUSIC_ALBUM As A_MUSIC_ALBUMDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableA_MUSIC_ALBUM = CType(Me.Table,A_MUSIC_ALBUMDataTable)
        End Sub
        
        Public Property ITEM_ID As String
            Get
                Try 
                    Return CType(Me(Me.tableA_MUSIC_ALBUM.ITEM_IDColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableA_MUSIC_ALBUM.ITEM_IDColumn) = value
            End Set
        End Property
        
        Public Property ALBUM_NAME As String
            Get
                Return CType(Me(Me.tableA_MUSIC_ALBUM.ALBUM_NAMEColumn),String)
            End Get
            Set
                Me(Me.tableA_MUSIC_ALBUM.ALBUM_NAMEColumn) = value
            End Set
        End Property
        
        Public Property ARTIST As String
            Get
                Try 
                    Return CType(Me(Me.tableA_MUSIC_ALBUM.ARTISTColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableA_MUSIC_ALBUM.ARTISTColumn) = value
            End Set
        End Property
        
        Public Property CATEGORY_ID As String
            Get
                Try 
                    Return CType(Me(Me.tableA_MUSIC_ALBUM.CATEGORY_IDColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableA_MUSIC_ALBUM.CATEGORY_IDColumn) = value
            End Set
        End Property
        
        Public Property LANGUAGE As String
            Get
                Try 
                    Return CType(Me(Me.tableA_MUSIC_ALBUM.LANGUAGEColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableA_MUSIC_ALBUM.LANGUAGEColumn) = value
            End Set
        End Property
        
        Public Function IsITEM_IDNull() As Boolean
            Return Me.IsNull(Me.tableA_MUSIC_ALBUM.ITEM_IDColumn)
        End Function
        
        Public Sub SetITEM_IDNull()
            Me(Me.tableA_MUSIC_ALBUM.ITEM_IDColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsARTISTNull() As Boolean
            Return Me.IsNull(Me.tableA_MUSIC_ALBUM.ARTISTColumn)
        End Function
        
        Public Sub SetARTISTNull()
            Me(Me.tableA_MUSIC_ALBUM.ARTISTColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCATEGORY_IDNull() As Boolean
            Return Me.IsNull(Me.tableA_MUSIC_ALBUM.CATEGORY_IDColumn)
        End Function
        
        Public Sub SetCATEGORY_IDNull()
            Me(Me.tableA_MUSIC_ALBUM.CATEGORY_IDColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsLANGUAGENull() As Boolean
            Return Me.IsNull(Me.tableA_MUSIC_ALBUM.LANGUAGEColumn)
        End Function
        
        Public Sub SetLANGUAGENull()
            Me(Me.tableA_MUSIC_ALBUM.LANGUAGEColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class A_MUSIC_ALBUMRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As A_MUSIC_ALBUMRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As A_MUSIC_ALBUMRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As A_MUSIC_ALBUMRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class A_MUSIC_STOCKDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnITEM_ID As DataColumn
        
        Private columnUNITS As DataColumn
        
        Private columnPRICE As DataColumn
        
        Private columnSUPPLIER_ID As DataColumn
        
        Friend Sub New()
            MyBase.New("A_MUSIC_STOCK")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property ITEM_IDColumn As DataColumn
            Get
                Return Me.columnITEM_ID
            End Get
        End Property
        
        Friend ReadOnly Property UNITSColumn As DataColumn
            Get
                Return Me.columnUNITS
            End Get
        End Property
        
        Friend ReadOnly Property PRICEColumn As DataColumn
            Get
                Return Me.columnPRICE
            End Get
        End Property
        
        Friend ReadOnly Property SUPPLIER_IDColumn As DataColumn
            Get
                Return Me.columnSUPPLIER_ID
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As A_MUSIC_STOCKRow
            Get
                Return CType(Me.Rows(index),A_MUSIC_STOCKRow)
            End Get
        End Property
        
        Public Event A_MUSIC_STOCKRowChanged As A_MUSIC_STOCKRowChangeEventHandler
        
        Public Event A_MUSIC_STOCKRowChanging As A_MUSIC_STOCKRowChangeEventHandler
        
        Public Event A_MUSIC_STOCKRowDeleted As A_MUSIC_STOCKRowChangeEventHandler
        
        Public Event A_MUSIC_STOCKRowDeleting As A_MUSIC_STOCKRowChangeEventHandler
        
        Public Overloads Sub AddA_MUSIC_STOCKRow(ByVal row As A_MUSIC_STOCKRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddA_MUSIC_STOCKRow(ByVal ITEM_ID As String, ByVal UNITS As Decimal, ByVal PRICE As Decimal, ByVal SUPPLIER_ID As String) As A_MUSIC_STOCKRow
            Dim rowA_MUSIC_STOCKRow As A_MUSIC_STOCKRow = CType(Me.NewRow,A_MUSIC_STOCKRow)
            rowA_MUSIC_STOCKRow.ItemArray = New Object() {ITEM_ID, UNITS, PRICE, SUPPLIER_ID}
            Me.Rows.Add(rowA_MUSIC_STOCKRow)
            Return rowA_MUSIC_STOCKRow
        End Function
        
        Public Function FindByITEM_ID(ByVal ITEM_ID As String) As A_MUSIC_STOCKRow
            Return CType(Me.Rows.Find(New Object() {ITEM_ID}),A_MUSIC_STOCKRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As A_MUSIC_STOCKDataTable = CType(MyBase.Clone,A_MUSIC_STOCKDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New A_MUSIC_STOCKDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnITEM_ID = Me.Columns("ITEM_ID")
            Me.columnUNITS = Me.Columns("UNITS")
            Me.columnPRICE = Me.Columns("PRICE")
            Me.columnSUPPLIER_ID = Me.Columns("SUPPLIER_ID")
        End Sub
        
        Private Sub InitClass()
            Me.columnITEM_ID = New DataColumn("ITEM_ID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnITEM_ID)
            Me.columnUNITS = New DataColumn("UNITS", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUNITS)
            Me.columnPRICE = New DataColumn("PRICE", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPRICE)
            Me.columnSUPPLIER_ID = New DataColumn("SUPPLIER_ID", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSUPPLIER_ID)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnITEM_ID}, true))
            Me.columnITEM_ID.AllowDBNull = false
            Me.columnITEM_ID.Unique = true
        End Sub
        
        Public Function NewA_MUSIC_STOCKRow() As A_MUSIC_STOCKRow
            Return CType(Me.NewRow,A_MUSIC_STOCKRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New A_MUSIC_STOCKRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(A_MUSIC_STOCKRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.A_MUSIC_STOCKRowChangedEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_STOCKRowChanged(Me, New A_MUSIC_STOCKRowChangeEvent(CType(e.Row,A_MUSIC_STOCKRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.A_MUSIC_STOCKRowChangingEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_STOCKRowChanging(Me, New A_MUSIC_STOCKRowChangeEvent(CType(e.Row,A_MUSIC_STOCKRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.A_MUSIC_STOCKRowDeletedEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_STOCKRowDeleted(Me, New A_MUSIC_STOCKRowChangeEvent(CType(e.Row,A_MUSIC_STOCKRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.A_MUSIC_STOCKRowDeletingEvent) Is Nothing) Then
                RaiseEvent A_MUSIC_STOCKRowDeleting(Me, New A_MUSIC_STOCKRowChangeEvent(CType(e.Row,A_MUSIC_STOCKRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveA_MUSIC_STOCKRow(ByVal row As A_MUSIC_STOCKRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class A_MUSIC_STOCKRow
        Inherits DataRow
        
        Private tableA_MUSIC_STOCK As A_MUSIC_STOCKDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableA_MUSIC_STOCK = CType(Me.Table,A_MUSIC_STOCKDataTable)
        End Sub
        
        Public Property ITEM_ID As String
            Get
                Return CType(Me(Me.tableA_MUSIC_STOCK.ITEM_IDColumn),String)
            End Get
            Set
                Me(Me.tableA_MUSIC_STOCK.ITEM_IDColumn) = value
            End Set
        End Property
        
        Public Property UNITS As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableA_MUSIC_STOCK.UNITSColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableA_MUSIC_STOCK.UNITSColumn) = value
            End Set
        End Property
        
        Public Property PRICE As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableA_MUSIC_STOCK.PRICEColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableA_MUSIC_STOCK.PRICEColumn) = value
            End Set
        End Property
        
        Public Property SUPPLIER_ID As String
            Get
                Try 
                    Return CType(Me(Me.tableA_MUSIC_STOCK.SUPPLIER_IDColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableA_MUSIC_STOCK.SUPPLIER_IDColumn) = value
            End Set
        End Property
        
        Public Function IsUNITSNull() As Boolean
            Return Me.IsNull(Me.tableA_MUSIC_STOCK.UNITSColumn)
        End Function
        
        Public Sub SetUNITSNull()
            Me(Me.tableA_MUSIC_STOCK.UNITSColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPRICENull() As Boolean
            Return Me.IsNull(Me.tableA_MUSIC_STOCK.PRICEColumn)
        End Function
        
        Public Sub SetPRICENull()
            Me(Me.tableA_MUSIC_STOCK.PRICEColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSUPPLIER_IDNull() As Boolean
            Return Me.IsNull(Me.tableA_MUSIC_STOCK.SUPPLIER_IDColumn)
        End Function
        
        Public Sub SetSUPPLIER_IDNull()
            Me(Me.tableA_MUSIC_STOCK.SUPPLIER_IDColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class A_MUSIC_STOCKRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As A_MUSIC_STOCKRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As A_MUSIC_STOCKRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As A_MUSIC_STOCKRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
